#!/bin/bash

source "$CONFIG_DIR/colors.sh"
PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####

sketchybar --bar position=top height=40 blur_radius=10 color=$BAR_COLOR

##### Changing Defaults #####

default=(
  y_offset=0
  padding_left=5
  padding_right=5
  blur_radius=10
  icon.font="GeistMono Nerd Font Propo:Regular:16.0"
  label.font=".AppleSystemUIFont:Semibold:14.0"
  icon.color=$WHITE
  label.color=$WHITE
  icon.padding_left=10
  icon.padding_right=0
  label.padding_left=10
  label.padding_right=10
  background.color=$ITEM_BG_COLOR
  background.corner_radius=3
  background.height=26
)
sketchybar --default "${default[@]}"

##### Left Items #####

sketchybar --add event aerospace_workspace_change

for WORKSPACE in B C M N; do
  PADDING_LEFT=3
  if [ "$WORKSPACE" = "B" ]; then
    PADDING_LEFT=-10
  fi

  sketchybar --add item "workspace.$WORKSPACE" left

  sketchybar --set "workspace.$WORKSPACE" \
    label="$WORKSPACE" \
    icon.drawing=off \
    width=dynamic \
    padding_left=$PADDING_LEFT \
    padding_right=3 \
    label.padding_left=8 \
    label.padding_right=8 \
    background.corner_radius=3 \
    background.height=26 \
    background.border_width=1 \
    script="$PLUGIN_DIR/aerospace_window_title.sh"

  sketchybar --subscribe "workspace.$WORKSPACE" aerospace_workspace_change
done

sketchybar \
          --add item front_app left \
          --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
          --subscribe front_app front_app_switched

##### Right Items #####

sketchybar \
  --add item clock right \
    --set clock \
      update_freq=10 \
      icon= \
      script="$PLUGIN_DIR/clock.sh" \
  \
  --add item wifi right \
    --set wifi \
      script="$PLUGIN_DIR/wifi.sh" \
      --subscribe wifi_change \
  \
  --add item volume right \
    --set volume \
      script="$PLUGIN_DIR/volume.sh" \
      --subscribe volume volume_change \
  \
  --add item battery right \
    --set battery \
      update_freq=120 \
      script="$PLUGIN_DIR/battery.sh" \
      --subscribe battery system_woke power_source_change \
  \
  --add item disk right \
    --set disk \
      script="$PLUGIN_DIR/disk.sh" \
      icon= \
      update_freq=3 \
      label.padding_left=0 \
      icon.padding_right=10 \
      label.color=$WHITE \
      icon.color=$WHITE \
  \
  --add graph cpu_usage right 50 \
     --set cpu_usage script="$PLUGIN_DIR/cpu_usage.sh" \
     update_freq=5 \
     label.color=$WHITE \
     graph.color=$WHITE \
     graph.fill_color=0xB3FFFFFF \
     graph.line_width=2 \
     icon.drawing=off

##### Force all scripts to run the first time #####
sketchybar --update

sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$(aerospace list-workspaces --focused)
